In [1]:
import pandas as pd
import datetime

In [2]:
r'''   
data_w_operacion: (DataFrame) data with their corresponding operacion (Entrada/Salida).
    path: C:\Users\ing_l\Tesis grado\Data\SUMO_data_w_operacion.csv

tandil_filtered_normalized: (DataFrame) weather information of Tandil from 01/01/2019 to 31/12/2019

'''

data_path = r'C:\Users\ing_l\Tesis grado\Data\SUMO_data_w_operacion.csv'
weather_path = r'C:\Users\ing_l\Tesis grado\Data\Weather data\tandil_filtered_normalized.csv'

In [3]:
dateweek_columns = ['id_cuadra','dia de semana', 'tiempo', 'ocupacion','operacion','estacion', 'fecha', 'FeelsLikeC', 'precipMM', 'windspeedKmph']

In [4]:
data = pd.read_csv(data_path, parse_dates=['fecha_tiempo'])
weather = pd.read_csv(weather_path, parse_dates=[['date','time']])

In [5]:
weather['time'] = weather['date_time'].apply(lambda x: x.hour)
weather['date'] = weather['date_time'].apply(lambda x: x.date())

In [6]:
data['dia de semana'] = data['fecha_tiempo'].apply(lambda x: pd.Timestamp(x).weekday())
data['tiempo'] = data['tiempo'].apply(lambda x: pd.Timestamp(x).time())
data['fecha'] = data['fecha'].apply(lambda x: pd.Timestamp(x).date())

In [7]:
#Me quedo con los que estan entre las 8 y las 21hs
data = data.loc[(data.tiempo > datetime.time(8)) & (data.tiempo < datetime.time(21))].reset_index(drop=True)

In [8]:
weather.rename(columns={'time': 'hora', 'date': 'fecha'}, inplace=True)

In [9]:
weather

,date_time,Unnamed: 0,FeelsLikeC,precipMM,windspeedKmph,hora,fecha
0,2019-01-01 06:00:00,2,0.446809,0.008621,0.195122,6,2019-01-01
1,2019-01-01 09:00:00,3,0.659574,0.008621,0.317073,9,2019-01-01
2,2019-01-01 12:00:00,4,0.765957,0.000000,0.292683,12,2019-01-01
3,2019-01-01 15:00:00,5,0.829787,0.000000,0.243902,15,2019-01-01
4,2019-01-01 18:00:00,6,0.787234,0.073276,0.073171,18,2019-01-01
...,...,...,...,...,...,...,...
2371,2019-12-31 09:00:00,3163,0.553191,0.000000,0.365854,9,2019-12-31
2372,2019-12-31 12:00:00,3164,0.595745,0.004310,0.195122,12,2019-12-31
2373,2019-12-31 15:00:00,3165,0.702128,0.012931,0.317073,15,2019-12-31
2374,2019-12-31 18:00:00,3166,0.680851,0.000000,0.317073,18,2019-12-31
2375,2019-12-31 21:00:00,3167,0.553191,0.000000,0.292683,21,2019-12-31

In [10]:
def get_weather_hour(t):
    if t < 9:
        return 6
    elif t < 12:
        return 9
    elif t < 15:
        return 12
    elif t < 18:
        return 15
    elif t < 21:
        return 18
    else:
        return 21

data['hora'] = data.tiempo.apply(lambda x: x.hour)
data['hora'] = data.hora.apply(get_weather_hour)

In [11]:
data

,id_cuadra,direccion,fecha,tiempo,ocupacion,lugares_cuadra,ocupacion_max,dispon_parq,altas_bajas(dia),fecha_tiempo,operacion,dia de semana,hora
0,2,General Pinto 545,2019-11-09,17:15:31,6,27.0,17,green,184,2019-09-11 17:15:31,NaN,2,15
1,2,General Pinto 545,2019-11-09,17:20:25,7,27.0,17,green,184,2019-09-11 17:20:25,Entrada,2,15
2,2,General Pinto 545,2019-11-09,17:34:54,6,27.0,17,green,190,2019-09-11 17:34:54,Salida,2,15
3,2,General Pinto 545,2019-11-09,17:40:09,5,27.0,17,green,191,2019-09-11 17:40:09,Salida,2,15
4,2,General Pinto 545,2019-11-09,17:45:05,6,27.0,17,green,192,2019-09-11 17:45:05,Entrada,2,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
275014,99,Av. EspaÃ±a 970,2019-11-12,12:14:21,4,NaN,7,green,30,2019-12-11 12:14:21,Salida,2,12
275015,99,Av. EspaÃ±a 970,2019-11-12,12:20:21,3,NaN,7,green,33,2019-12-11 12:20:21,Salida,2,12
275016,99,Av. EspaÃ±a 970,2019-11-12,12:30:06,4,NaN,7,green,36,2019-12-11 12:30:06,Entrada,2,12
275017,99,Av. EspaÃ±a 970,2019-11-12,12:40:22,3,NaN,7,green,39,2019-12-11 12:40:22,Salida,2,12
275018,99,Av. EspaÃ±a 970,2019-11-12,12:44:11,2,NaN,7,green,40,2019-12-11 12:44:11,Salida,2,12

In [13]:
data = data.merge(weather[['FeelsLikeC', 'precipMM', 'windspeedKmph', 'fecha', 'hora']], how='left', on=['fecha','hora'])

In [14]:
data

,id_cuadra,direccion,fecha,tiempo,ocupacion,lugares_cuadra,ocupacion_max,dispon_parq,altas_bajas(dia),fecha_tiempo,operacion,dia de semana,hora,FeelsLikeC,precipMM,windspeedKmph
0,2,General Pinto 545,2019-11-09,17:15:31,6,27.0,17,green,184,2019-09-11 17:15:31,NaN,2,15,0.638298,0.000000,0.317073
1,2,General Pinto 545,2019-11-09,17:20:25,7,27.0,17,green,184,2019-09-11 17:20:25,Entrada,2,15,0.638298,0.000000,0.317073
2,2,General Pinto 545,2019-11-09,17:34:54,6,27.0,17,green,190,2019-09-11 17:34:54,Salida,2,15,0.638298,0.000000,0.317073
3,2,General Pinto 545,2019-11-09,17:40:09,5,27.0,17,green,191,2019-09-11 17:40:09,Salida,2,15,0.638298,0.000000,0.317073
4,2,General Pinto 545,2019-11-09,17:45:05,6,27.0,17,green,192,2019-09-11 17:45:05,Entrada,2,15,0.638298,0.000000,0.317073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281026,99,Av. EspaÃ±a 970,2019-11-12,12:14:21,4,NaN,7,green,30,2019-12-11 12:14:21,Salida,2,12,0.531915,0.056034,0.463415
281027,99,Av. EspaÃ±a 970,2019-11-12,12:20:21,3,NaN,7,green,33,2019-12-11 12:20:21,Salida,2,12,0.531915,0.056034,0.463415
281028,99,Av. EspaÃ±a 970,2019-11-12,12:30:06,4,NaN,7,green,36,2019-12-11 12:30:06,Entrada,2,12,0.531915,0.056034,0.463415
281029,99,Av. EspaÃ±a 970,2019-11-12,12:40:22,3,NaN,7,green,39,2019-12-11 12:40:22,Salida,2,12,0.531915,0.056034,0.463415
281030,99,Av. EspaÃ±a 970,2019-11-12,12:44:11,2,NaN,7,green,40,2019-12-11 12:44:11,Salida,2,12,0.531915,0.056034,0.463415

In [ ]:
'''
La idea de la red seria que de input tenga fecha_tiempo (o por ahi mejor, solo dia de la semana), 
la ocupacion de esa fecha_tiempo, el clima.
Como output deberia tener la ocupacion de ese momento.

Aparte a todo eso se deberia ver la ocupacion actual y la ocupacion maxima para saber si hay lugar libre.
'''

def to_seconds(time):
    '''transform datetime.time to seconds'''
    return time.hour * 60 * 60 + time.minute * 60 + time.second

def normalize_time(time):
    '''normalize time (in seconds) to values bertween 0 and 1'''
    max_time = 23 * 60 * 60 + 59 * 60 + 59
    return time / max_time

def modify_operation(operation):
    '''if operacion == Entrada sets value to 1, == NaN sets to 0 and == Salida sets to -1'''
    if operation == 'Entrada':
        return 1
    if operation == 'Salida':
        return -1
    return 0

def normalize_ocupation(row):
    '''normalize ocupation to values between 0 and 1, using the lugares_cuadra value'''
    global max_ocup
    return (row['ocupacion'] / max_ocup)

def get_season(fecha):
    fecha = pd.to_datetime(fecha, dayfirst=True)
    d = fecha.day
    m = fecha.month * 100
    md = m + d
    season = 0
    if ((md >= 921) and (md <= 1220)):
        season = 0  # spring
    elif ((md >= 1221) and (md <= 320)):
        season = 1  # summer
    elif ((md >= 321) and (md <= 620)):
        season = 2  # fall
    elif ((md >= 621) and (md <= 920)):
        season = 3  # winter
    return season

data_week = data.loc[:, ['id_cuadra','dia de semana', 'tiempo', 'ocupacion','operacion','fecha', 'FeelsLikeC', 'precipMM', 'windspeedKmph']]
data_week['tiempo'] = data_week['tiempo'].apply(to_seconds)
data_week['operacion'] = data_week['operacion'].apply(modify_operation)
data_week['estacion'] = data_week['fecha'].apply(get_season)

max_ocup = data['lugares_cuadra'].max()
data_week['ocupacion'] = data_week.apply(normalize_ocupation, axis=1)
data_week = data_week.loc[:, dateweek_columns]

In [ ]:
data_week