In [2]:
import os
import zipfile
import pandas as pd
import numpy as np
from IPython.display import display, HTML, clear_output
from datetime import datetime
import shutil

In [4]:
def get_date(d):
    return d[:10]

def get_time(d):
    return d[12:-1]

def encode_operation(o):
    if 'SALIDA' in o or 'CIERRE' in o:
        return 0
    elif 'INGRESO' in o:
        return 1
    return -1

data_path = r'C:\Users\ing_l\Tesis grado\Data\SUMO'
directories = [x[0] for x in os.walk(data_path)]
directories = directories[1:]

data = pd.DataFrame(columns=['parquimetro', 'fecha_emision', 'tiempo_emision', 'operacion', 'tiempo_estacionado', 'direccion', 'latitud', 'longitud'])
for d in directories:
    clear_output()
    print(d)
    os.chdir(d)
    files = [x[2] for x in os.walk(d)][0]
    #print(files)
    for f in files:
        print(f)
        zf = zipfile.ZipFile(f)
        detalle = zf.namelist()[0]
        zf.extract(detalle)
        os.chdir(d + '\\DETALLE')
        file_name = detalle[8:]
        os.system('"C:\\Program Files\\LibreOffice\\program\\soffice" --headless --convert-to xlsx {}'.format(file_name))
        df = pd.read_excel(d + '\\DETALLE' + '\\' + file_name + 'x')
        df.columns = df[2:].iloc[0]
        df.columns.name = ''
        df = df[3:].reset_index(drop=True)
        if not pd.isna(df.columns[0]):
            df_to = df.loc[df['Parquímetro'] == 'Parquímetro'].index[0]
            df = df[:df_to]
            df.dropna(inplace=True)
            df['fecha_emision'] = df['Fecha Emisión'].apply(get_date)
            df['tiempo_emision'] = df['Fecha Emisión'].apply(get_time)
            df['Operación'] = df['Operación'].apply(encode_operation)
            df = df[['Parquímetro', 'fecha_emision', 'tiempo_emision', 'Operación', 'Tiempo Estacionamiento', 'Dirección', 'Latitud', 'Longitud']]
            df.rename(columns={'Parquímetro': 'parquimetro',
                              'Operación': 'operacion',
                              'Tiempo Estacionamiento': 'tiempo_estacionado',
                              'Dirección': 'direccion',
                              'Latitud': 'latitud',
                              'Longitud': 'longitud'}, inplace=True)
            data = data.append(df, ignore_index=True)
        zf.close()
        os.chdir(d)
        shutil.rmtree(d + '\\DETALLE')

C:\Users\ing_l\Tesis grado\Data\SUMO\12- Diciembre
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_01_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_02_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_03_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_04_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_05_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_06_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_07_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_08_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_09_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_10_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_11_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_12_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_13_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_14_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_15_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_16_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_17_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_18_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_19_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_20_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_21_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_22_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_23_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_24_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_25_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_26_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_27_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_28_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_29_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_30_12_2019.zip
CLEARING_ESTACIONAMIENTO_MEDIDO_DIA_31_12_2019.zip

In [5]:
data.to_csv(r'C:\Users\ing_l\Tesis grado\Data\SUMO\full_SUMO_data.csv', index=False)

In [6]:
data

,parquimetro,fecha_emision,tiempo_emision,operacion,tiempo_estacionado,direccion,latitud,longitud
0,20016,01-01-2019,10:55:00,0,10:00,Belgrano 660,-37.328838,-59.134455
1,20060,01-01-2019,16:25:00,1,0:00,Chacabuco 357,-37.328143,-59.136740
2,20060,01-01-2019,16:25:00,0,0:00,Chacabuco 357,-37.328143,-59.136740
3,20060,01-01-2019,16:25:00,1,0:00,Chacabuco 357,-37.328143,-59.136740
4,20060,01-01-2019,17:11:00,0,0:46,Chacabuco 357,-37.328143,-59.136740
...,...,...,...,...,...,...,...,...
2957537,20061,31-12-2019,13:20:00,0,0:38,Yrigoyen 847,-37.323967,-59.139628
2957538,20061,31-12-2019,13:28:00,0,2:22,Yrigoyen 847,-37.323967,-59.139628
2957539,20061,31-12-2019,13:28:00,1,2:22,Yrigoyen 847,-37.323967,-59.139628
2957540,20061,31-12-2019,13:28:00,0,2:22,Yrigoyen 847,-37.323967,-59.139628
2957541,20061,31-12-2019,13:35:00,0,1:39,Yrigoyen 847,-37.323967,-59.139628

In [5]:
full_sumo_data_path = r'C:\Users\ing_l\Tesis grado\Data\SUMO\full_SUMO_data.csv'
data = pd.read_csv(full_sumo_data_path)
data.loc[data.parquimetro == 20000]

,parquimetro,fecha_emision,tiempo_emision,operacion,tiempo_estacionado,direccion,latitud,longitud
1849,20000,02-01-2019,09:35:00,1,0:00,Belgrano 768,-37.326435,-59.131628
1850,20000,02-01-2019,09:39:00,1,0:00,Belgrano 768,-37.326435,-59.131628
1851,20000,02-01-2019,09:41:00,1,0:00,Belgrano 768,-37.326435,-59.131628
1852,20000,02-01-2019,09:45:00,0,0:06,Belgrano 768,-37.326435,-59.131628
1853,20000,02-01-2019,09:45:00,0,0:03,Belgrano 768,-37.326435,-59.131628
...,...,...,...,...,...,...,...,...
2956469,20000,31-12-2019,12:32:00,1,0:00,Belgrano 768,-37.326648,-59.131743
2956470,20000,31-12-2019,12:35:00,0,0:06,Belgrano 768,-37.326648,-59.131743
2956471,20000,31-12-2019,12:48:00,0,0:26,Belgrano 768,-37.326648,-59.131743
2956472,20000,31-12-2019,12:57:00,0,0:25,Belgrano 768,-37.326648,-59.131743
2956473,20000,31-12-2019,13:25:00,0,1:01,Belgrano 768,-37.326648,-59.131743